sudo: required
services:
  - docker

before_install:
 - docker build -t tuliomonteiro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tuliomonteiro/react-test npm test -- --coverage

after_success:
  - docker build -t tuliomonteiro/multi-client ./client
  - docker build -t tuliomonteiro/multi-nginx ./nginx
  - docker build -t tuliomonteiro/multi-server ./server
  - docker build -t tuliomonteio/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tuliomonteiro/multi-client
  - docker push tuliomonteiro/multi-nginx
  - docker push tuliomonteiro/multi-server
  - docker push tuliomonteiro/multi-worker

deploy:
  provider: elasticbeanstalk
  regio: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-760877605459
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

